service: serverless-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: "dev"
  region: "sa-east-1"
  environment:
    DYNAMODB_TABLE: Amazon-Books-Bestsellers-DB
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
            - dynamodb:DescribeTable
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  getProducts:
    handler: src/handlers/getBooks.handler
    events:
      - http:
          path: products
          method: get

  refreshProducts:
    handler: src/handlers/refreshProducts.handler
    events:
      - http:
          path: refresh
          method: post

resources:
  Resources:
    BooksDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST